CREATE TABLE RecAreas(
  "KEYWORDS" varchar(1024) NULL,
  "LASTUPDATEDDATE" varchar(1024) NULL,
  "ORGRECAREAID" INTEGER NULL,
  "RECAREAEMAIL" varchar(1024) NULL,
  "RECAREAFEEDESCRIPTION" varchar(1024) NULL,
  "RECAREAID" INTEGER NULL,
  "RECAREALATITUDE" numeric(10,6) NULL,
  "RECAREALONGITUDE" numeric(10,6) NULL,
  "RECAREANAME" varchar(1024) NULL,
  "RECAREAPHONE" varchar(1024) NULL,
  "RECAREARESERVATIONURL" varchar(1024) NULL,
  "STAYLIMIT" varchar(1024) NULL
);

.mode csv ,
.import Data/RecAreas_API_v1_edited.csv RecAreas
